---
docker_apt_url: "{{ 'http://obs.linaro.org/ERP:/17.12/Debian_9' if ansible_architecture == 'aarch64' else 'https://download.docker.com/linux/ubuntu' }}"
docker_apt_key_file: "{{ 'Release.key' if ansible_architecture == 'aarch64' else 'gpg' }}"
docker_apt_key_id: "{{ 'C32DA102AD89C2BE' if ansible_architecture == 'aarch64' else '0EBFCD88' }}"

docker_yum_url: "https://yum.dockerproject.org"
docker_gpg_fingerprint: "58118E89F3A912897C070ADBF76221572C52609D"

customize_etc_hosts: True

create_kolla_user: True
create_kolla_user_sudoers: "{{ create_kolla_user }}"

kolla_user: "kolla"
kolla_group: "kolla"

enable_host_ntp: False

change_selinux: True

selinux_state: "permissive"

docker_storage_driver: ""

docker_custom_option: ""

docker_runtime_directory: ""

debian_pkg_install:
 - docker-ce
 - git
 - python-setuptools
 - python-pip
 - ntp

redhat_pkg_install:
 - epel-release
 - docker-engine-1.12.0
 - git
 - python-setuptools
 - ntp
 - sudo

ubuntu_pkg_removals:
 - lxd
 - lxc
 - libvirt-bin
 - open-iscsi

redhat_pkg_removals:
 - libvirt
 - libvirt-daemon
 - iscsi-initiator-utils

# Path to a virtualenv in which to install python packages. If None, a
# virtualenv will not be used.
virtualenv:

# Whether the virtualenv will inherit packages from the global site-packages
# directory. This is typically required for modules such as yum and apt which
# are not available on PyPI.
virtualenv_site_packages: True